### ISSUE TITLE
Listing images should be an object list?

### ISSUE THREAD

**Issue by thenikso** [Antlos/AntlosAPI#1]
@essediweb writes:

> images è una lista di immagini non meglio definite...a te vanno bene così (senza una specifica della tipologia, tipo main, ecc. o serve in qualche maniera tipizzarle?

**Comment by thenikso** [comment]
Le API mi sembrano usabili. Una cosa però, il POST per prendere la cartella dove mettere le immagini di un listing come si usa se voglio aggiungere un'immagine a quel listing in un secondo momento?

**Comment by essediweb** [comment]
Il flusso che ho disegnato è praticamente lo stesso che abbiami usato in qk....
Le immagini sono in relazione ManyToOne con i listing, per cui puoi fare tutti i post /image che vuoi in relazione ad un listing. Poi sul get /listing ritorniamo embeddati nella response la lista di key s3 e quanto ti serve per riottenere tutte le immagini, cos' hai tutto con una unica request.

**Comment by thenikso** [comment]
Concludendo, ok per la object list così possiamo anche supportare servizi esterni
